// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MostafaProject.infrastructure.Context;

#nullable disable

namespace MostafaProject.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231030063255_Initial_Database")]
    partial class Initial_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MostafaProject.Domain.Entities.Demo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime");

                    b.Property<Guid>("Created_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("Modified_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Created_At");

                    b.HasIndex("Is_Deleted");

                    b.ToTable("Demo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18c07aa4-58cb-46e3-b214-288168903bec"),
                            Created_At = new DateTime(2023, 10, 30, 8, 32, 55, 585, DateTimeKind.Local).AddTicks(2003),
                            Created_by = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Demo Discription",
                            Is_Deleted = false,
                            Name = "Demo Name",
                            Notes = "Demo Note"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
